spring:
  application:
    name: security-security
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres  # URL для подключения к PostgreSQL
    driverClassName: org.postgresql.Driver
    username: postgres  # Имя пользователя для PostgreSQL
    password: 123  # Пароль для PostgreSQL
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
